### ISSUE TITLE
I got banned in 000webhost

### ISSUE THREAD

**Issue by KindofSHT** [vian21/facebook-mobile-phisher#1]
Please make a new html anti ban

**Comment by vian21** [comment]
Hey Imjek,
The app was made for educational purposes, and hacking(Phishing) remains illegal. Most domain providers will take down your site after some days. You can either create another account with them or ask them to unban you, telling them it was just a test and for educational purposes. They may unlock it.

Another way would be to host it on your own websever or tunnelling apps such as Ngrok.io ,..

Best of luck.
